# Generated by Django 4.2.7 on 2023-12-28 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='variant2',
        ),
        migrations.AddField(
            model_name='cars',
            name='variant2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.variant'),
            preserve_default=False,
        ),
    ]
