# Generated by Django 4.2.7 on 2023-12-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_remove_cars_variant2_cars_variant2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='variant2',
            new_name='variant',
        ),
    ]
