# Generated by Django 4.2.7 on 2023-12-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_rename_variant2_cars_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='info',
        ),
        migrations.AddField(
            model_name='cars',
            name='Colors',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='fueltank',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
