# Generated by Django 4.2.7 on 2023-12-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_remove_cars_info_cars_colors_cars_fueltank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='fueltank',
            new_name='feature1',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='mileage',
            new_name='feature2',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='Colors',
        ),
        migrations.AddField(
            model_name='cars',
            name='feature3',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='feature4',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='feature5',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='feature6',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='feature7',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='feature8',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='feature9',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
